### ISSUE TITLE
Push to Bioconductor?

### ISSUE THREAD

**Issue by seandavi** [seandavi/BiocPkgTools#14]
@vjcitn, @lshep, do the two of you think it is worth pushing this into Bioconductor as a package? Right now, it is "unofficial", but I think it could be useful and might get a little input from other users.

**Comment by lshep** [comment]
I think it could be useful as an "official" Bioconductor package but your call.

**Comment by vjcitn** [comment]
consider adding some functionality to recommend biocviews here  which might
then get into bioccheck    i am finding multiple cancer oriented packages
that lack cancer among their views

**Comment by vjcitn** [comment]
FYI I have submitted a PR with BiocInstaller dependencies removed, and BiocManager functionality applied

**Comment by seandavi** [comment]
Contributed to Bioconductor last night.
