### ISSUE TITLE
biocExplorer not embedding in vignette

### ISSUE THREAD

**Issue by seandavi** [seandavi/BiocPkgTools#18]
I don't know what the problem is, but at least on my Mac Chrome browser, including `biocExplorer()` as an example in the vignette leads to empty plots. Might be a conflict with visNetwork javascript?

**Comment by Shians** [comment]
I've actually never tried it in markdown, was hoping the magic of `htmlwidgets` will take care of it. I'll take a look at this when I can.

**Comment by Shians** [comment]
Fixed in #20.
