### ISSUE TITLE
Testing new DOI creation by Bioc core team

### ISSUE THREAD

**Issue by seandavi** [seandavi/BiocPkgTools#2]
Hi, @lshep.

```
library(BiocPkgTools)
pl = getBiocPkgList()
z = mapply(FUN = generateBiocPkgDOI,pl$Package,pl$Author,2017,testing=TRUE)
```

Run it with `testing=TRUE`. Then, you can login to https://ezid.lib.purdue.edu/ with the username/password combo of apitest/apitest to list the DOIs that are created. You can get a sense of how things go for you. 

Ideally, when running for "real", DOIs are updated if they exist and created if not. I need to give you the credentials for running for real, which we can do offline.

**Comment by lshep** [comment]
Okay. Thank you.

**Comment by lshep** [comment]
So would I want to run this and generate with both release and devel?

**Comment by seandavi** [comment]
Ideally, we capture all packages in Bioc, regardless of "version". If it has a landing page (even from previous releases), it should have a DOI. In other words, run on both. That way, everything should end up with a DOI. The DOIs are not version-sensitive, so a package in devel and the same package in release will have only one DOI.

**Comment by lshep** [comment]
I was able to run and create DOI for annotation packages and experiment packages utilizing the new repo argument.
