### ISSUE TITLE
Author names a bit of a mess

### ISSUE THREAD

**Issue by Shians** [seandavi/BiocPkgTools#27]
Unfortunately the authors field is a bit of a Wild West in terms of what people put in there. At the moment the Authors field is a `list` of `character` which is the way to go, however each token in the list should try to represent an author. This is currently not the case since tokens are split by `"\\s?,\\s?"` which gets tripped up by `[aut, ctb]` or the word "and", and retains all sorts of weird things like emails, orchid profile links and whatever weirdness people have decided to insert.

This leads to a curious lineup of Bioconductor's most prolific authors.

```
library(BiocPkgTools)

x <- biocPkgList()

x$Author %>%
    unlist() %>%
    table() %>%
    sort(decreasing = TRUE) %>%
    head()

## cre] aut] cph]  cre ths] ctb] 
## 298   39   27   26   21   16 
```

I'm hoping to clean this up a bit with an upcoming pull request, it's essentially impossible to do this well in general since there are packages that have decided to split the author list by periods and many contain sentences explaining an author's contribution. But at the very least it's not too hard to take care of the simple cases. At the moment this is my prototype

```
library(BiocPkgTools)
library(magrittr)
library(purrr)
library(stringr)

x <- biocPkgList()

# reassemble authors for re-processing
authors <- x$Author %>%
    map_chr(function(x) paste(x, collapse = ", "))

authors_cleaned <- authors %>%
    str_replace_all("\n", " ") %>%
    str_remove_all("\\[.*?\\]") %>%
    str_remove_all("<.*?>") %>%
    str_remove_all("\\(.*?\\)") %>%
    str_squish() %>%
    str_replace_all("\\w* contributions ?\\w*", ", ") %>%
    str_replace_all("\\sand\\s", ", ") %>%
    str_replace_all(",\\s+,", ",") %>%
    str_replace_all(",+", ",")

authors_cleaned %>%
    sample(200)
```

`authors_cleaned` will behave a bit better with `str_split`

```
authors_list <- map(
    authors_cleaned,
    function(x) {
        str_trim(str_split(x, ",", simplify = TRUE))
    }
)

authors_list %>% unlist() %>% table() %>% sort(decreasing = TRUE) %>% head()
##   Martin Morgan   Wolfgang Huber Robert Gentleman    Laurent Gatto     R. Gentleman      Hervé Pagès 
##              31               21               20               18               17               16 
```

**Comment by seandavi** [comment]
This is a really nice update, @Shians. Thanks again for the help.

**Comment by LiNk-NY** [comment]
@Shians 
Are you looking for all package authors or just the maintainer? 
There are some functions that get you half way there. 

For the maintainer:
`utils::maintainer()`

For all the authors: 
`desc::desc("pkg/folder")$get_authors()`

**Comment by seandavi** [comment]
Just to add a bit of context, @LiNk-NY, we gather the package metadata from *all* packages from online sources and return those as a dataframe. Packages do not need to be installed to use BiocPkgTools. What @Shians was referring to is that there are many variants of maintainer and author text and that makes "computing" on those fields a bit challenging. 

Take a look at the following to get a sense of what is at work:

```
library(BiocPkgTools)
bpl = biocPkgList()
head(bpl$Maintainer)
head(bpl$Author)
```

**Comment by seandavi** [comment]
I'm going to close this for now, but we can reopen if some other magic comes along.
