### ISSUE TITLE
F1000 REVIEW: Things I spotted while reviewing

### ISSUE THREAD

**Issue by HenrikBengtsson** [seandavi/BiocPkgTools#34]
I'm reviewing the F1000 submission.  While doing this I spotted a few "random" things related to the package per se.  I figured it's more convenient to just post these things here rather than via the review process.  If I spot more, I'll post them to this issue.

## Help pages

* [ ] A few \title{}:s are in all lower case, e.g. "get bioconductor download stats". Easy to spot if you look at the HTML index page.

* [ ] The help pages use all lower case for the value sections, e.g. "a character string of the email" in help("biocBuildEmail").  Is that intentional?

* [ ] Bioconductor is sometimes referred to as 'bioconductor' (lower case) or just 'bioc' and 'Bioc'.

* [ ] xml -> XML (for the initialism XML)

* [ ] github -> GitHub

* [ ] The help pages could need some more cross links.  For example, help(dataciteXMLGenerate) says the value us "an xml element", e.g. exactly what is an "xml element". A link to the corresponding \pkg{XML} or \pkg{xml2} documentation would be helpful.

# Vignette

* [ ] Broken URL:  https://bioconductor.org/packages/3.9/BiocViews in Section 6.3 'Integration with [BiocViews]' (in the header) - automatically detected by `R CMD check --as-cran` (awesome flag; hint, hint, nudge, nudge to the Bioconductor community)

**Comment by HenrikBengtsson** [comment]
# Miscellaneous

* [ ] Is dependency 'SnowballC' used anywhere? A 'grep' on all files didn't give anything.

* [ ] `spelling::spell_check_package()` reveals several typos/spelling mistakes.

* [ ] Several URLs used in the package code uses the HTTP although HTTPS is available/supported for them.

* [ ] Does the internal `download.file()` call need a `mode = "wb"` to avoid obscure misbehaviors due to different newline endings?

**Comment by LiNk-NY** [comment]
Hi Henrik, @HenrikBengtsson 
I've made some changes in PR #42. 

> * [x]  A few \title{}:s are in all lower case, e.g. "get bioconductor download stats". Easy to spot if you look at the HTML index page.
> * [x]  The help pages use all lower case for the value sections, e.g. "a character string of the email" in help("biocBuildEmail").  Is that intentional?
> * [x]  Bioconductor is sometimes referred to as 'bioconductor' (lower case) or just 'bioc' and 'Bioc'.
> * [x]  xml -> XML (for the initialism XML)
> * [x]  github -> GitHub
> * [ ]  The help pages could need some more cross links.  For example, help(dataciteXMLGenerate) says the value us "an xml element", e.g. exactly what is an "xml element". A link to the corresponding \pkg{XML} or \pkg{xml2} documentation would be helpful.
> 
> # Vignette
> * [ ]  Broken URL:  https://bioconductor.org/packages/3.9/BiocViews in Section 6.3 'Integration with [BiocViews]' (in the header) - automatically detected by `R CMD check --as-cran` (awesome flag; hint, hint, nudge, nudge to the Bioconductor community)
>
> # Miscellaneous
> * [ ]  Is dependency 'SnowballC' used anywhere? A 'grep' on all files didn't give anything.
> * [ ]  `spelling::spell_check_package()` reveals several typos/spelling mistakes.
> * [x]  Several URLs used in the package code uses the HTTP although HTTPS is available/supported for them.
> * [ ]  Does the internal `download.file()` call need a `mode = "wb"` to avoid obscure misbehaviors due to different newline endings?
