### ISSUE TITLE
'DESCRIPTION' is a file, not a directory

### ISSUE THREAD

**Issue by mtmorgan** [seandavi/BiocPkgTools#39]
This lines tests for directory existence, but should be `file.exists()` https://github.com/seandavi/BiocPkgTools/blob/3a152243d3e949dae676f5fe3aff2087ba2b3943/R/getPackageInfo.R#L17 . Would be a good opportunity to develop a unit test for this function?

@FelixErnst

**Comment by FelixErnst** [comment]
should be fixed. unit test is included in the PR as well

**Comment by seandavi** [comment]
Thx a bunch, @mtmorgan and @FelixErnst.
