### ISSUE TITLE
unable to run buildPkgDependencyDataFrame

### ISSUE THREAD

**Issue by LiNk-NY** [seandavi/BiocPkgTools#43]
I'm having an issue when building the vignette during `R CMD build BiocPkgTools`: 

https://github.com/seandavi/BiocPkgTools/blob/ded6804c67c64dfc2df2931dff7ecc109531af28/vignettes/BiocPkgTools.Rmd#L273-L279

I'm using this version of R:

```r
sessionInfo()
R Under development (unstable) (2020-01-03 r77629)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.10
```

## Error
```r
Quitting from lines 274-279 (BiocPkgTools.Rmd) 
Error: processing vignette 'BiocPkgTools.Rmd' failed with diagnostics:
ReadItem: unknown type 50, perhaps written by later version of R
--- failed re-building ‘BiocPkgTools.Rmd’

SUMMARY: processing the following file failed:
  ‘BiocPkgTools.Rmd’

Error: Vignette re-building failed.
Execution halted
```

Perhaps this is an issue with a serialized dataset in the that is too old for R devel? 
See here: 
https://github.com/seandavi/BiocPkgTools/blob/ded6804c67c64dfc2df2931dff7ecc109531af28/R/biocPkgList.R#L99-L100

@seandavi @rcastelo

**Comment by rcastelo** [comment]
hi, this is really strange because the RDS file you refer to is CRAN's file for information about packages at the URL http://cran.r-project.org/web/packages/packages.rds which is directly read by `biocPkgList()`. I could build and check without errors on the following R-devel:

```
R Under development (unstable) (2020-02-06 r77774) -- "Unsuffered Consequences"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin16.7.0 (64-bit)
```

which is a month older than yours, i'll update my R-devel and will see if i can reproduce the error.

**Comment by rcastelo** [comment]
hi again, i've updated my R-devel and i could not reproduce the error. actually, i've just noticed that i was reading wrongly the date of your R-devel, which is not a month newer than it was mine, but a month older, so maybe you should update your R-devel:

```
R Under development (unstable) (2020-03-12 r77934) -- "Unsuffered Consequences"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin16.7.0 (64-bit)

[...]

library(BiocPkgTools)
Loading required package: htmlwidgets
depdf <- buildPkgDependencyDataFrame(repo=c("BioCsoft", "CRAN"),
+                                      dependencies=c("Depends", "Imports")) 
pkgDepMetrics("GenomicScores", depdf)
              ImportedAndUsed Exported Usage DepOverlap
Biostrings                  1      240  0.42       0.19
Biobase                     1      128  0.78       0.09
XML                         2      176  1.14       0.03
utils                       4      215  1.86       0.01
BiocGenerics                3      139  2.16       0.07
IRanges                    10      254  3.94       0.11
GenomeInfoDb                6       60 10.00       0.17
AnnotationHub               4       34 11.76       0.86
S4Vectors                  34      268 12.69       0.10
GenomicRanges              17      105 16.19       0.21
```

**Comment by LiNk-NY** [comment]
Hi Robert, @rcastelo 
Yes, it looks like my older version of R was having issues with the file. 
I've updated it and was able to build. Thanks!
```r
sessionInfo()
R Under development (unstable) (2020-03-12 r77934)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 19.10
```
