### ISSUE TITLE
adding elapsed time to the host/package/phase report table

### ISSUE THREAD

**Issue by vjcitn** [seandavi/BiocPkgTools#59]
See https://github.com/Bioconductor/BBS/issues/112#issuecomment-1009722767

If a uniform unit (seconds) can be employed then making the time column numeric would be appropriate. Not a super high priority at the moment but those numbers will be used when available in the package.

**Comment by LiNk-NY** [comment]
One thing to note is that I haven't looked for this metadata below versions `3.14`...
