### ISSUE TITLE
Cache can lead to stale results

### ISSUE THREAD

**Issue by mikelove** [seandavi/BiocPkgTools#68]
I don't have an example, but I was seeing 0's for downloads for recent months and then realized I needed to remove the rows in BiocFileCache (manually with bfcremove) in order to re-download the stats.

**Comment by LiNk-NY** [comment]
Hi Mike, 
Thanks for pointing this out. Perhaps it was resolved in https://github.com/seandavi/BiocPkgTools/commit/58b37dff7ac9b0c47c5735785bc303700b92b0a8 ?
Best,
Marcel

**Comment by mikelove** [comment]
I'm on release branch, it's likely resolved by that. Thanks Marcel!

**Comment by LiNk-NY** [comment]
Thanks for the reminder! I'll port it over to release shortly.

**Comment by LiNk-NY** [comment]
@mikelove 
It should be available in version `1.16.1`. Let me know if you are still seeing this. 
Thanks!
