### ISSUE TITLE
Failing on Bioc devel

### ISSUE THREAD

**Issue by bschilder** [seandavi/BiocPkgTools#70]
Hello, 

Just wanted to give you a heads up that `BiocPkgTools` is failing on devel, causing my package `rworkflows` to fail as well.
http://bioconductor.org/checkResults/devel/bioc-LATEST/BiocPkgTools/
https://github.com/neurogenomics/rworkflows/issues/65

Would be great to get this working again! (I'm in the midst of publishing `rworkflows`).

Thanks, 
Brian

**Comment by LiNk-NY** [comment]
Hi Brian, 
We are aware. The stats have been a bit unreliable lately. 
I've added a patch to filter out invalid URLs 
cfebeae2ddc3d2f4b1ec1de7c22110d36786001b
Best,
Marcel

**Comment by bschilder** [comment]
Amazing, thanks so much for addressing this so quickly!
