### ISSUE TITLE
Error when stats page is not available

### ISSUE THREAD

**Issue by llrs** [seandavi/BiocPkgTools#71]
Many thanks for this great package. I found a problem with `biocDownloadStats`:

``` r
BiocManager::valid()
#> 'getOption("repos")' replaces Bioconductor standard repositories, see
#> 'help("repositories", package = "BiocManager")' for details.
#> Replacement repositories:
#>     BioCsoft: https://bioconductor.org/packages/3.18/bioc
#>     CRAN: https://ftp.cixug.es/CRAN
#> [1] TRUE
BiocManager::version()
#> [1] '3.18'
packageVersion("BiocPkgTools")
#> [1] '1.20.0'
BiocPkgTools::biocDownloadStats()
#> 'getOption("repos")' replaces Bioconductor standard repositories, see
#> 'help("repositories", package = "BiocManager")' for details.
#> Replacement repositories:
#>     BioCsoft: https://bioconductor.org/packages/3.18/bioc
#>     CRAN: https://ftp.cixug.es/CRAN
#> Error in if (identical(nrow(bquery), 1L) && bfcneedsupdate(bfc, bquery[["rid"]])) tryCatch({: missing value where TRUE/FALSE needed
```
<sup>Created on 2024-01-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

It fails because https://bioconductor.org/packages/stats/data-experiment/experiment_pkg_stats.tab is not (currently) available.
I am not sure if this is due to the recent problems with the Bioconductor stats or something else.
But in these cases ` bfcneedsupdate(bfc, bquery[["rid"]])` from .cache_read returns NA in the condition.

I am not sure if I should report that to BiocFileCache.

**Comment by LiNk-NY** [comment]
Thanks, this was resolved in c4b889f8e7f279b725388c5491ddb0a9c88dd648
